const PDFDocument = require('pdfkit');
const streamBuffers = require('stream-buffers');

/**
 * Generates an in-memory PDF buffer for the given report data
 * @param {Object} reportData - Report content to render in the PDF
 * @returns {Promise<Buffer>} - A buffer containing the PDF bytes
 */
exports.generatePDF = async (reportData) => {
  const doc = new PDFDocument();
  const stream = new streamBuffers.WritableStreamBuffer({
    initialSize: 100 * 1024,  // start at 100KB
    incrementAmount: 10 * 1024 // grow by 10KB as needed
  });

  doc.pipe(stream);

  // --- PDF Header ---
  doc.fontSize(20).text('Team Performance Report', { align: 'center' });
  doc.moveDown();

  doc.fontSize(12).text(`Team ID: ${reportData.teamId}`);
  doc.text(`Generated by: ${reportData.generatedBy || 'Unknown'}`);
  doc.text(`Generated at: ${new Date(reportData.generatedAt || Date.now()).toLocaleString()}`);
  doc.moveDown();

  // --- Filters Section ---
  if (reportData.filters && Object.keys(reportData.filters).length > 0) {
    doc.fontSize(12).text('Filters Applied:', { underline: true });
    Object.entries(reportData.filters).forEach(([key, value]) => {
      doc.text(`• ${key}: ${value}`);
    });
    doc.moveDown();
  } else {
    doc.fontSize(12).text('Filters Applied: None');
    doc.moveDown();
  }

  // --- Member Statistics ---
  if (reportData.memberStats) {
    doc.fontSize(12).text('Member Statistics:', { underline: true });
    reportData.memberStats.forEach(member => {
      doc.text(`• ${member.name || 'N/A'} - Completed: ${member.tasksCompleted || 0}`);
    });
    doc.moveDown();
  }

  // --- Task Summary ---
  if (reportData.taskSummary) {
    const { total, completed, percent } = reportData.taskSummary;
    doc.text(`Task Summary: ${completed}/${total} completed (${percent}%)`);
  }

  // Finalize PDF
  doc.end();

  await new Promise(resolve => doc.on('end', resolve));

  // ✅ Use getContents() to safely retrieve buffer
  const buffer = stream.getContents();
  if (!buffer) throw new Error('Failed to generate PDF buffer');
  return buffer;
};
